// <auto-generated />
using FactorioHelper.EFCore.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FactorioHelper.Models.Migrations
{
    [DbContext(typeof(SQLiteContext))]
    partial class SQLiteContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.10");

            modelBuilder.Entity("FactorioHelper.Models.Item", b =>
                {
                    b.Property<long>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AmountCrafted")
                        .HasColumnType("INTEGER");

                    b.Property<double>("AmountPerSec")
                        .HasColumnType("REAL");

                    b.Property<int>("IsAssemblingMachine")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<double>("TimeToCraft")
                        .HasColumnType("REAL");

                    b.HasKey("ItemId");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("Ingredient", b =>
                {
                    b.Property<int>("AmountNeeded")
                        .HasColumnType("INTEGER");

                    b.Property<double>("TimeToCraftMainItem")
                        .HasColumnType("REAL");

                    b.Property<long>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("AmountNeededPerSec")
                        .HasColumnType("REAL");

                    b.Property<long>("MainItemId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AmountNeeded", "TimeToCraftMainItem", "ItemId");

                    b.HasIndex("ItemId");

                    b.HasIndex("MainItemId");

                    b.ToTable("Ingredients");
                });

            modelBuilder.Entity("Ingredient", b =>
                {
                    b.HasOne("FactorioHelper.Models.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FactorioHelper.Models.Item", null)
                        .WithMany("Ingredients")
                        .HasForeignKey("MainItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("FactorioHelper.Models.Item", b =>
                {
                    b.Navigation("Ingredients");
                });
#pragma warning restore 612, 618
        }
    }
}
